# Generated by Django 2.0 on 2018-02-01 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_it_was_happend', models.CharField(max_length=100)),
                ('detail_education', models.CharField(max_length=200)),
                ('education_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_site', models.URLField()),
                ('when_it_was_happend', models.CharField(max_length=100)),
                ('job_detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_detail_first_part', models.CharField(max_length=200)),
                ('skill_detail_second_part', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=200)),
                ('new_link', models.URLField()),
                ('new_detail', models.CharField(max_length=200)),
                ('new_detail_name', models.CharField(max_length=200)),
                ('when_it_was_happend', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='avatar')),
                ('job_name', models.CharField(max_length=200)),
                ('detail_profile', models.TextField()),
                ('repository', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('debian', models.URLField()),
                ('python', models.URLField()),
                ('postgresql', models.URLField()),
                ('jquery', models.URLField()),
                ('bootstrap', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Side_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_link', models.URLField()),
                ('project_link_name', models.CharField(max_length=200)),
                ('project_detail', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_projects', to='cv.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='cv.Profile'),
        ),
        migrations.AddField(
            model_name='main_qualifications',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_qualifications', to='cv.Profile'),
        ),
        migrations.AddField(
            model_name='job_experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_experience', to='cv.Profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv.Profile'),
        ),
    ]
